/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated/inspections.index'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated/inspections.new'
import { Route as AuthenticatedInspectionsIdRouteImport } from './routes/_authenticated/inspections.$id'
import { Route as AuthenticatedInspectionsIdIndexRouteImport } from './routes/_authenticated/inspections.$id.index'
import { Route as AuthenticatedInspectionsIdEditRouteImport } from './routes/_authenticated/inspections.$id.edit'
import { Route as AuthenticatedInspectionsIdSpacesSpaceIdRouteImport } from './routes/_authenticated/inspections.$id.spaces.$spaceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectionsRoute,
  } as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInspectionsRoute,
  } as any)
const AuthenticatedInspectionsIdRoute =
  AuthenticatedInspectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInspectionsRoute,
  } as any)
const AuthenticatedInspectionsIdIndexRoute =
  AuthenticatedInspectionsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectionsIdRoute,
  } as any)
const AuthenticatedInspectionsIdEditRoute =
  AuthenticatedInspectionsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInspectionsIdRoute,
  } as any)
const AuthenticatedInspectionsIdSpacesSpaceIdRoute =
  AuthenticatedInspectionsIdSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedInspectionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/inspections': typeof AuthenticatedInspectionsRouteWithChildren
  '/inspections/$id': typeof AuthenticatedInspectionsIdRouteWithChildren
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/inspections/$id/edit': typeof AuthenticatedInspectionsIdEditRoute
  '/inspections/$id/': typeof AuthenticatedInspectionsIdIndexRoute
  '/inspections/$id/spaces/$spaceId': typeof AuthenticatedInspectionsIdSpacesSpaceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/inspections/$id/edit': typeof AuthenticatedInspectionsIdEditRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdIndexRoute
  '/inspections/$id/spaces/$spaceId': typeof AuthenticatedInspectionsIdSpacesSpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inspections/$id': typeof AuthenticatedInspectionsIdRouteWithChildren
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/inspections/$id/edit': typeof AuthenticatedInspectionsIdEditRoute
  '/_authenticated/inspections/$id/': typeof AuthenticatedInspectionsIdIndexRoute
  '/_authenticated/inspections/$id/spaces/$spaceId': typeof AuthenticatedInspectionsIdSpacesSpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inspections'
    | '/inspections/$id'
    | '/inspections/new'
    | '/inspections/'
    | '/inspections/$id/edit'
    | '/inspections/$id/'
    | '/inspections/$id/spaces/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/inspections/new'
    | '/inspections'
    | '/inspections/$id/edit'
    | '/inspections/$id'
    | '/inspections/$id/spaces/$spaceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/inspections'
    | '/_authenticated/'
    | '/_authenticated/inspections/$id'
    | '/_authenticated/inspections/new'
    | '/_authenticated/inspections/'
    | '/_authenticated/inspections/$id/edit'
    | '/_authenticated/inspections/$id/'
    | '/_authenticated/inspections/$id/spaces/$spaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedInspectionsRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedInspectionsRoute
    }
    '/_authenticated/inspections/$id': {
      id: '/_authenticated/inspections/$id'
      path: '/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof AuthenticatedInspectionsIdRouteImport
      parentRoute: typeof AuthenticatedInspectionsRoute
    }
    '/_authenticated/inspections/$id/': {
      id: '/_authenticated/inspections/$id/'
      path: '/'
      fullPath: '/inspections/$id/'
      preLoaderRoute: typeof AuthenticatedInspectionsIdIndexRouteImport
      parentRoute: typeof AuthenticatedInspectionsIdRoute
    }
    '/_authenticated/inspections/$id/edit': {
      id: '/_authenticated/inspections/$id/edit'
      path: '/edit'
      fullPath: '/inspections/$id/edit'
      preLoaderRoute: typeof AuthenticatedInspectionsIdEditRouteImport
      parentRoute: typeof AuthenticatedInspectionsIdRoute
    }
    '/_authenticated/inspections/$id/spaces/$spaceId': {
      id: '/_authenticated/inspections/$id/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/inspections/$id/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedInspectionsIdSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedInspectionsIdRoute
    }
  }
}

interface AuthenticatedInspectionsIdRouteChildren {
  AuthenticatedInspectionsIdEditRoute: typeof AuthenticatedInspectionsIdEditRoute
  AuthenticatedInspectionsIdIndexRoute: typeof AuthenticatedInspectionsIdIndexRoute
  AuthenticatedInspectionsIdSpacesSpaceIdRoute: typeof AuthenticatedInspectionsIdSpacesSpaceIdRoute
}

const AuthenticatedInspectionsIdRouteChildren: AuthenticatedInspectionsIdRouteChildren =
  {
    AuthenticatedInspectionsIdEditRoute: AuthenticatedInspectionsIdEditRoute,
    AuthenticatedInspectionsIdIndexRoute: AuthenticatedInspectionsIdIndexRoute,
    AuthenticatedInspectionsIdSpacesSpaceIdRoute:
      AuthenticatedInspectionsIdSpacesSpaceIdRoute,
  }

const AuthenticatedInspectionsIdRouteWithChildren =
  AuthenticatedInspectionsIdRoute._addFileChildren(
    AuthenticatedInspectionsIdRouteChildren,
  )

interface AuthenticatedInspectionsRouteChildren {
  AuthenticatedInspectionsIdRoute: typeof AuthenticatedInspectionsIdRouteWithChildren
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
}

const AuthenticatedInspectionsRouteChildren: AuthenticatedInspectionsRouteChildren =
  {
    AuthenticatedInspectionsIdRoute:
      AuthenticatedInspectionsIdRouteWithChildren,
    AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
    AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  }

const AuthenticatedInspectionsRouteWithChildren =
  AuthenticatedInspectionsRoute._addFileChildren(
    AuthenticatedInspectionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
